# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simForward <- function(x, tpm, N) {
    .Call('_miniEpiMod_simForward', PACKAGE = 'miniEpiMod', x, tpm, N)
}

