# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simForwardR <- function(rt, time_steps, tpm_base) {
    .Call('_miniEpiMod_simForwardR', PACKAGE = 'miniEpiMod', rt, time_steps, tpm_base)
}

